# Generated by Django 3.2.10 on 2023-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0030_alter_ticket_created_alter_ticket_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nidanticket',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='nidanticket',
            name='call_start',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
