# Generated by Django 3.2.10 on 2023-08-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0032_auto_20230819_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmu',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.city'),
        ),
    ]
